from .settings import *  # noqa

SIMPLE_JWT["ISSUER"] = None
SIMPLE_JWT["JWK_URL"] = None

# Only used for unit tests! NEVER use this private key in production!

SIMPLE_JWT[
    "SIGNING_KEY"
] = """
-----BEGIN RSA PRIVATE KEY-----
MIICXgIBAAKBgQC6AryudTYrBrhxb7/kvUULQIs/hgOEpi9GD1VJxDlP0XlzYnpt
aHVPC2tNLWCh/icCuFfBJfNO5ST8MuuIA/MVckVUlYDqUvLHkgObAmB1ZjUIdbjQ
Nm+oTvWZ8MN3aDFKzCnUgoRCeJt57m7J0L4A5vV2MwMqhNcDvLHvuA8l/QIDAQAB
AoGAEvt0hdkwTfPBntHoo08tXJiZnUHv2fmbmWq3KW/86UhXPI8wLzoZvpdLu/SF
iAKHuJ9XVT6qNcLso1AO+TJt+/WDyYfvutHObdPLtmD6b6G5DjHQd67DJ8kMmN42
x9/Pxvjjtie6jYwYhKBaIqLqsbmYMjMoQ+bTbo4s+kWtJAECQQDyiqKz6Soxn1At
uWOE8rWq2sHp61WiUhdhZog6NNSMcjT+BDWZmQrE6WLtYweMPgkawjun4yirSxq9
FnouDfh1AkEAxFUQ+R+bUzEvCeVjGZHcDRZMQSLbX6SqLuwWMuVeoAv+M2cwO5I2
OPm3vIACEv6Qvli/nu9asDt5eQqZkkuGaQJBALir7m5mHoZh8z6dZbUYyFIq9nMR
iMZrEvpKg3cuOpglbUvsEJO+/4Am4/gz6s9RfMUvFxUh1Rl3ugg3URg38vECQQC+
IY9VYtl+AFSIZd/JxGpxNhXUwpfmEMZKuJFq6pvvrI2ZZCXemuLt3E+mOeVIVcUA
wVuY5D1UC9TAdpZwibl5AkEAtfL5st5FoAbXdKHbc9rmbsWZJwlVlMK9rvm+KIAt
E6TMixxd8mw4G9K81FCMQ6nFS3Yh8WUWKQkJ2nIfF9yBGA==
-----END RSA PRIVATE KEY-----
"""

SIMPLE_JWT[
    "VERIFYING_KEY"
] = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC6AryudTYrBrhxb7/kvUULQIs/hgOEpi9GD1VJxDlP0XlzYnptaHVPC2tNLWCh/icCuFfBJfNO5ST8MuuIA/MVckVUlYDqUvLHkgObAmB1ZjUIdbjQNm+oTvWZ8MN3aDFKzCnUgoRCeJt57m7J0L4A5vV2MwMqhNcDvLHvuA8l/Q=="
